#
# Makefile for the focaltech touchscreen drivers.
#

# Each configuration option enables a list of files.


obj-$(CONFIG_TOUCHSCREEN_FTS_M1000) += focaltech_upgrade_ft8006u.o
obj-$(CONFIG_TOUCHSCREEN_FTS_M1000) += focaltech_upgrade_ft8613.o